# Generated by Django 5.2.8 on 2026-03-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_remove_userprofile_bio_remove_userprofile_location_and_more'),
        ('kanmind_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='boards', to='auth_user.userprofile'),
        ),
    ]
