# Generated by Django 5.2.8 on 2026-03-10 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0002_alter_board_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='name',
            new_name='title',
        ),
    ]
