# Generated by Django 5.2.8 on 2026-03-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0004_alter_task_assignee_alter_task_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='members',
            new_name='member',
        ),
    ]
