# Generated by Django 5.2.8 on 2026-03-11 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0005_rename_members_board_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='member',
            new_name='members',
        ),
    ]
