# Generated by Django 5.2.8 on 2026-03-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0007_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
