# Generated by Django 5.2.8 on 2026-03-11 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_remove_userprofile_bio_remove_userprofile_location_and_more'),
        ('kanmind_app', '0008_remove_task_created_at_remove_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_boards', to='auth_user.userprofile'),
        ),
    ]
