# Generated by Django 5.2.8 on 2026-03-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0009_board_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
