# Generated by Django 5.2.8 on 2026-03-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0010_rename_owner_board_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
