# Generated by Django 5.2.8 on 2026-03-11 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_remove_userprofile_bio_remove_userprofile_location_and_more'),
        ('kanmind_app', '0013_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='auth_user.userprofile'),
        ),
    ]
